
model_name: AilmV1

use_wandb: True

rng_seed: 42
# If you delete this the trainer will calculate the chinchilla optimal number of tokens.
# token_budget: 4.0e+6
# Easily override these for testing.
# step_count: 2000
# gradient_accumulation_steps: 12

# Set a memory limit of 30gib. MacOS will hang if the compute graph balloons above the size of RAM.
memory_limit: 32212254720

# The number of batches to run validation over.
validation_batches: 50

model_config:
  # use_value_residual_technique: true

# To determine a solid learning rate schedule I did a survey of various model papers and consulted the
# Huggingface Smol Training Playbook
# Playbook: https://huggingface.co/spaces/HuggingFaceTB/smol-training-playbook#scaling-laws-for-hyperparameters
# Survey: https://docs.google.com/spreadsheets/d/1mTQkUpaVkdVNfDkuHVeTPam0ERx-XIXm_8Dy2JUf1qk/edit?usp=sharing
learning_rate_schedule:
  kind: trapezoid
  # Used by nanochat
  learning_rate_max: 0.02
  learning_rate_min: 0.002
  warmup_percent: 5
  rampdown_percent: 5
  # warmup_steps: 2000
  # rampdown_steps: 2000

optimizer:
  name: muon
  # nanochat uses 0.0
  weight_decay: 0.0
  muon_momentum: 0.95
  # Widely used in the survey and recommended by Karpathy and Smollm
  gradient_norm_clipping: 1.0

training_data_loader:
  kind: synth_combo
  directory: datasets/pleias_synth/
  shuffle: true

# I took the last, smaller parquet file from fineweb edu 20B and called it a validation set.
validation_data_loader:
  kind: synth_combo
  directory: datasets/pleias_synth/validate/
  shuffle: true

batching:
  # Modern LLMs use sequence lengths of around 2048-4096.
  # However, to train on my laptop it's important to keep the memory requirements small, and increasing this will cause quadratic growth of the attention matrix.
  sequence_length: 1024
  # 0.5e6 rounded up to be a multiple of sequences_per_micro_batch * sequence_length
  tokens_per_batch: 503808
  # Since I'm compute bound, on my M1 Max both 4 and 8 get similar performance, but 4 uses less RAM.
  # 4 also leads to less variance in tokens per second.
  sequences_per_micro_batch: 4


# Intervals at which to perform various expensive tasks.
# These are expressed in terms of full batch steps, not microbatch steps.
intervals:
  save_interval: 100
  validation_interval: 100
  log_interval: 1
  inference_interval: 100


tokenizing:
  tokenizer_name: gpt2
  tokenizer_queue_length: 8
  encoder_stall_seconds: 300
  trainer_stall_seconds: 300

inference:
    prompt: "The mind is"
    max_tokens_to_generate: 10
    max_batches: 4
    k: 4
    temperature: 0.5
